// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdkgnnkkrsdnbiznfmpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJka2dubmtrcnNkbmJpem5mbXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDg5NDAsImV4cCI6MjA3MDU4NDk0MH0.wHdFIFUUiwWFMQHQQkA5p1jJt1OZpsHn_p_cTq3qGYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});